name: Build and publish Docker Images to GitHub Container registry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Build docker image
      - run: |-
          docker build --tag gurimoa:${{ github.sha }}
      - name: Login to GitHub package registry
      - run: |-
          docker login ghcr.io -u Magi-KS -p ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub package registry
      - run: |-
          docker push gurimoa:${{ github.sha }}
