name: Build and publish Docker Images to GitHub Container registry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image and Publish to GitHub package registry
        run: |
          export DOCKER_IMAGE_NAME_WITH_TAG=$(echo ghcr.io/${{ github.repository }}/gurimoa:${{ github.sha }} | tr '[:upper:]' '[:lower:]')
          docker build --tag $DOCKER_IMAGE_NAME_WITH_TAG .
          docker login ghcr.io -u Magi-KS -p ${{ secrets.GITHUB_TOKEN }}
          docker push $DOCKER_IMAGE_NAME_WITH_TAG
      - uses: azure/setup-kubectl@v1
        name: Install kubectl
        with:
          version: 'v1.22.2' # default is latest stable
        id: install
      - name: Deploy to Kubernetes cluster
        run: |
          echo ${{ secrets.KRABBYPATTYSECRETSAUCE }} > /tmp/kbptssauce
          envsubst < .kube/gurimoa-deployment.yaml | kubectl apply --kubeconfig /tmp/kbptssauce -f -
